module.exports = class Constrains {

    MMTOPT = 2.83465;
    

    DOCUMENT_WIDTH = 216;
    DOCUMENT_HEIGHT = 303;

    DOCUMENT_MARGIN_LEFT = 20 * this.MMTOPT;
    DOCUMENT_MARGIN_RIGHT =  20 * this.MMTOPT;
    
    DOCUMENT_MARGIN_TOP_FOLD_MARK = 105 * this.MMTOPT;
    DOCUMENT_MARGIN_TOP_HOLE_MARK = 148.5 * this.MMTOPT;   

    IMAGE_MARGIN_LEFT = 125 * this.MMTOPT;
    IMAGE_HEIGHT = 40 * this.MMTOPT;
    IMAGE_WIDTH = (this.DOCUMENT_WIDTH * this.MMTOPT ) - this.DOCUMENT_MARGIN_RIGHT - this.IMAGE_MARGIN_LEFT; 

    ADRESS_HEIGHT = 45 * this.MMTOPT;
    ADRESS_WIDTH = 85 * this.MMTOPT;
    ADRESS_MARGIN_LEFT = 25 * this.MMTOPT;

    INFO_BLOCK_MARGIN_RIGHT = 10 * this.MMTOPT;
    INFO_BLOCK_WIDTH = 80 * this.MMTOPT;
    INFO_BLOCK_HEIGHT = this.ADRESS_HEIGHT - (5 * this.MMTOPT);

    TEXTFIELD_MARGIN_TOP = 107 * this.MMTOPT;
    TEXTFIELD_MARGIN_LEFT = 25 * this.MMTOPT;
    TEXTFIELD_MARGIN_RIGHT = 20 * this.MMTOPT;

    TEXTFIELD_WIDTH = (this.DOCUMENT_WIDTH * this.MMTOPT) - this.TEXTFIELD_MARGIN_LEFT - this.TEXTFIELD_MARGIN_RIGHT;

}