const MMTOPT = 2.83465;

/* eslint-disable */
module.exports = {

    MMTOPT: 2.83465,

    DOCUMENT_WIDTH:  216,
    DOCUMENT_HEIGHT: 303,

    DOCUMENT_MARGIN_LEFT: 20 * MMTOPT,
    DOCUMENT_MARGIN_RIGHT: 20 * MMTOPT,

    DOCUMENT_MARGIN_TOP_FOLD_MARK: 105 * MMTOPT,
    DOCUMENT_MARGIN_TOP_HOLE_MARK: 148.5 * MMTOPT,   

    IMAGE_MARGIN_LEFT: 125 * MMTOPT,
    IMAGE_HEIGHT: 40 * MMTOPT,
    IMAGE_WIDTH: (216 * MMTOPT ) - 145 * MMTOPT, 

    ADRESS_HEIGHT: 45 * MMTOPT,
    ADRESS_WIDTH: 85 * MMTOPT,
    ADRESS_MARGIN_LEFT: 25 * MMTOPT,

    INFO_BLOCK_MARGIN_RIGHT: 10 * MMTOPT,
    INFO_BLOCK_WIDTH: 80 * MMTOPT,
    INFO_BLOCK_HEIGHT: 45 * MMTOPT - (5 * MMTOPT),

    TEXTFIELD_MARGIN_TOP: 107 * MMTOPT,
    TEXTFIELD_MARGIN_LEFT: 25 * MMTOPT,
    TEXTFIELD_MARGIN_RIGHT: 20 * MMTOPT,

    TEXTFIELD_WIDTH: (216 * MMTOPT) - (25 * MMTOPT) - (20 * MMTOPT),
}
